# HMM Foward-Backward Algorithm

In [5]:
from PattRecClasses import DiscreteD, GaussD, HMM, MarkovChain
from matplotlib import pyplot as plt

import numpy as np

# State generator

# Finite HMM
mc = MarkovChain( np.array( [ 1, 0 ] ), np.array( [ [ 0.9, 0.1, 0.0 ], [ 0.0, 0.9, 0.1 ] ] ) ) 
# Infinite HMM
#mc = MarkovChain( np.array( [ 0.75, 0.25 ] ), np.array( [ [ 0.99, 0.01 ], [ 0.03, 0.97 ] ] ) ) 
g1 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g2 = GaussD( means=[3], stdevs=[2] )   # Distribution for state = 2
h  = HMM( mc, [g1, g2]) 

# Generating the conditional probability Matrix
x = [-0.2,2.6,1.3]
px = np.zeros((2,3))
px = [[g1.prob(x[0]), g1.prob(x[1]), g1.prob(x[2])], [g2.prob(x[0]), g2.prob(x[1]), g2.prob(x[2])]]
print("px: \n",px)

# Scaling the matrix
k = np.max(px,0)
for j in range(3):
    for i in range(2):
        px[i][j] = px[i][j]/k[j]

# Foward algorithm
alpha,c = mc.forward(px)
print("alphahat: \n",alpha)
print("c: \n",c)

# Backward algorithm
betahat = mc.backward(px,c)
print("betahat: \n",betahat)

px: 
 [[array([0.39104269]), array([0.01358297]), array([0.17136859])], [array([0.05546042]), array([0.19552135]), array([0.13899244])]]
alphahat: 
 [[1.         0.38470424 0.41887466]
 [0.         0.61529576 0.58112534]]
c: 
 [1.         0.16252347 0.82658096 0.05811253]
betahat: 
 [[1.         1.03893571 0.        ]
 [8.41537925 9.35042138 2.08182773]]
